language: android
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

before_install:
  - chmod +x gradlew
  - echo yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew mobile:check
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
